CREATE TABLE OFFLINEAPP.ORDDTL ( 
	ORID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	ORDTLID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	ORPRID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	ORQTY DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	ORPRICE DECIMAL(7, 2) NOT NULL DEFAULT 0 )   
	  
	RCDFMT ORDDTLF    ; 
  
LABEL ON TABLE OFFLINEAPP.ORDDTL 
	IS 'Order detail' ; 
  
LABEL ON COLUMN OFFLINEAPP.ORDDTL 
( ORID TEXT IS 'Order Id' , 
	ORDTLID TEXT IS 'Detail Id' , 
	ORPRID TEXT IS 'Product Id' , 
	ORQTY TEXT IS 'Quantity Ordered' , 
	ORPRICE TEXT IS 'Price' ) ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON OFFLINEAPP.ORDDTL TO PUBLIC ;   
