CREATE TABLE OFFLINEAPP.ORDHDR ( 
	OHID decimal(5, 0) NOT NULL generated always as identity
(start with 1 increment by 1),
	OHDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	PRIMARY KEY( OHID ) )   
	  
	RCDFMT ORDHDRF    ; 
  
LABEL ON TABLE OFFLINEAPP.ORDHDR 
	IS 'Order header' ; 
  
LABEL ON COLUMN OFFLINEAPP.ORDHDR 
( OHID TEXT IS 'Order Id' , 
	OHDATE TEXT IS 'Order Date' ) ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON OFFLINEAPP.ORDHDR TO PUBLIC ;  
